# -*- coding: utf-8 -*-
"""04_lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gH9vpDMFt2I6VTCsC_G75-ABVRMMdSlO
"""

### Lists ###

# Definicion

my_list = list()
my_other_list = []

print(len(my_list))

my_list = [35, 24, 62, 52,30, 30, 17]

print(my_list)
print(len(my_list))

my_other_list = [35, 1.17, "Fermin", "garcia"]

print(type(my_list))
print(type(my_other_list))

# Acceso a elementos y busqueda

print(my_other_list(0))
print(my_other_list(1))
print(my_other_list(-1))
print(my_other_list(-4))
print(my_list.count(30)
# print(my_other_list[4])
# print(my_other_list(-5))

print(my_other_list.index("fermin"))

age, height, name, surname = my_other_list
print(nme)

name, height, age, surname = my_other_list[2], my_other_list[0], my_other_list[3]
print(age)

# concatenacion

print(my_list + my_other_list)
# print(my_list - my_other_list)

# creacion, isertacion, actualizacion, alinacion

my_other_list.append("CECyTEM")
print(my_other_list)

my_other_list.insert(1, "ROJO")
prin(my_other_list)

my_other_list[1] = "AZUL"
prin(my_other_list)

my_other_list.remove("AZUL")
prin(my_other_list)

my_list.remove("30")
print(my_list)

my_list = [35, 24, 62, 52, 30, 30, 17m]
my_other_list = [35, 1.77, "Fermin", "Garcia"]

# operaciones con listas

my_new_list = my_list.copy()

my_list.clear()
print(my_list)

my_new_list.reverse()
print(my_new_list)

my_new_list.sort()
print(my_new_list)

# Sublistas


print(my_new_list(1:3))