# -*- coding: utf-8 -*-
"""05_Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rizHvhDo5bPG6cU-8fxLs2lTxv0WNGYe
"""

### Tuples ###

# Definicion

my_tuple = tuple()
my_other_tuple = ()

my_tuple = (35, 1.77, "Fermin", "Garcia", "Profesor")
my_other_tuple = (35, 60, 30)

print(my_tuple)
print(type(my_tuple))

# Acceso a elementos y busqueda

print(my_tuple[0])
print(my_tuple[-1])
# print(my_tuple[5]) # IndexError
# print(my_tuple[-6]) # IndexError

print(my_tuple.count("Fermin"))
print(my_tuple.index("Garcia"))
print(my_tuple.index("Profesor"))

# my_tuple[1] = 1.80 # 'tuple' object does not support item assignment

# Concatenacion

my_sum_tuple = my_tuple + my_other_tuple
print(my_sum_tuple)

# Subtuplas

print(my_sum_tuple[3:6])

# Tupla mutable con conversion a lista

my_tuple = list(my_tuple)
print(type(my_tuple))


my_tuple = (35, 1.77, "Fermin", "Garcia", "Profesor")
my_other_tuple = (35, 60, 30)

my_tuple[4] = "CECyTEM"
my_tuple.insert(1, "Azul")
my_tuple = tuple(my_tuple)
print(my_tuple)
print(type(my_tuple))

# Eliminacion

# del my_tuple[2] TypeError: 'tuple' object doesn't support item deletion

del my_tuple
# print(my_tuple) NameError: name 'my_tuple' is not defined