# -*- coding: utf-8 -*-
"""07_Dicts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VrwwRFkeFmYa82Z2m38G3ZwdYig2cSLj
"""

### Dictionaries ###

# Definicion

my_dict = dict()
my_other_dict = {}

print(type(my_dict))
print(type(my_other_dict))

my_other_dict = {"Nombre": "Fermin",
                 "Apellido": "Garcia", "Edad": 35, 1: "Python"}

my_dict = {
  "Nombre": "Fermin",
  "Apellido": "Garcia",
  "Edad": 35,
  "Lenguajes": {"Python", "Swift", "Kotlin"},
  1: 1.77
}

print(my_other_dict)
print(my_dict)

print(len(my_other_dict))
print(len(my_dict))

# Busqueda

print(my_dict[1])
print(my_dict["Nombre"])

print("Garcia" in my_dict)
print("Apellido" in my_dict)

# Insercion

my_dict["Calle"] = "Calle Garcia"
print(my_dict)

# Actualizacion

my_dict["Nombre"] = "Jorge"
print(my_dict["Nombre"])

# Eliminacion

del my_dict["Calle"]
print(my_dict)

# Otras operaciones

print(my_dict.items())
print(my_dict.keys())
print(my_dict.values())

my_list = ["Nombre", 1, "Piso"]

my_new_dict = dict.fromkeys((my_list))
print(my_new_dict)
my_new_dict = dict.fromkeys(("Nombre", 1, "Piso"))
print((my_new_dict))
my_new_dict = dict.fromkeys(my_dict)
print((my_new_dict))
my_new_dict = dict.fromkeys(my_dict, "Garcia")
print((my_new_dict))

my_values = my_new_dict.values()
print(type(my_values))